#!/bin/zsh
set -euo pipefail

export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"

CONTENTS_DIR="$(cd "$(dirname "$0")/.." && pwd)"
BUILD_INFO="$CONTENTS_DIR/Resources/build-info.env"
BOOTSTRAP_PATH="$CONTENTS_DIR/Resources/beta-bootstrap.sh"
APP_SUPPORT="$HOME/Library/Application Support/DubLocal"
SOURCE_ROOT="$APP_SUPPORT/app"
VENV="$SOURCE_ROOT/.venv"
PYTHON="$VENV/bin/python"
APP_HOME="$HOME/.dublocal"
LOG_DIR="$APP_HOME/logs"
BOOTSTRAP_LOG="$LOG_DIR/bootstrap.log"
REPO_URL="https://github.com/ArrowSK/dublocal.git"
EXPECTED_BRANCH="main"
SETUP_MARKER="$APP_SUPPORT/bootstrap-revision"
SETUP_CHANGED=0

mkdir -p "$APP_SUPPORT" "$LOG_DIR"
exec >>"$BOOTSTRAP_LOG" 2>&1

echo "--- DubLocal beta bootstrap $(date -u '+%Y-%m-%dT%H:%M:%SZ') ---"

BETA_VERSION="0.6.0b3"
BUILD_SHA=""
if [[ -f "$BUILD_INFO" ]]; then
  # build-info.env is generated by DubLocal's own packaging script and contains only
  # shell-safe version/SHA values.
  source "$BUILD_INFO"
fi

notify() {
  /usr/bin/osascript -e 'on run argv' \
    -e 'display notification (item 1 of argv) with title "DubLocal Beta"' \
    -e 'end run' "$1" >/dev/null 2>&1 || true
}

show_message() {
  /usr/bin/osascript -e 'on run argv' \
    -e 'display dialog (item 1 of argv) with title "DubLocal Beta" buttons {"OK"} default button "OK"' \
    -e 'end run' "$1" >/dev/null 2>&1 || true
}

ask_yes_no() {
  local message="$1"
  local answer
  answer="$(/usr/bin/osascript -e 'on run argv' \
    -e 'button returned of (display dialog (item 1 of argv) with title "DubLocal Beta" buttons {"Not now", "Continue"} default button "Continue" cancel button "Not now")' \
    -e 'end run' "$message" 2>/dev/null || true)"
  [[ "$answer" == "Continue" ]]
}

fail() {
  echo "ERROR: $1"
  show_message "$1\n\nNothing in your finished DubLocal outputs was changed.\n\nSetup log: $BOOTSTRAP_LOG"
  exit 1
}

find_python() {
  local candidate path
  for candidate in python3.13 python3.12 python3.11 python3; do
    path="$(command -v "$candidate" 2>/dev/null || true)"
    if [[ -n "$path" ]] && "$path" -c 'import sys; raise SystemExit(0 if (3, 11) <= sys.version_info < (3, 14) else 1)' >/dev/null 2>&1; then
      printf '%s\n' "$path"
      return 0
    fi
  done
  for path in \
    /opt/homebrew/opt/python@3.13/bin/python3.13 \
    /opt/homebrew/opt/python@3.12/bin/python3.12 \
    /opt/homebrew/opt/python@3.11/bin/python3.11 \
    /usr/local/opt/python@3.13/bin/python3.13 \
    /usr/local/opt/python@3.12/bin/python3.12 \
    /usr/local/opt/python@3.11/bin/python3.11; do
    if [[ -x "$path" ]] && "$path" -c 'import sys; raise SystemExit(0 if (3, 11) <= sys.version_info < (3, 14) else 1)' >/dev/null 2>&1; then
      printf '%s\n' "$path"
      return 0
    fi
  done
  return 1
}

ensure_git() {
  if command -v git >/dev/null 2>&1 && git --version >/dev/null 2>&1; then
    return 0
  fi
  if command -v brew >/dev/null 2>&1; then
    if ask_yes_no "DubLocal needs Git for its managed installation and in-app updater. Install Git with Homebrew now?"; then
      brew install git || fail "Homebrew could not install Git."
      return 0
    fi
    fail "Git is required for this beta. Reopen DubLocal after installing Git."
  fi
  /usr/bin/xcode-select --install >/dev/null 2>&1 || true
  fail "Git is not available. macOS has been asked to open the Command Line Tools installer. Finish that installation, then open DubLocal again."
}

ensure_python_base() {
  local found
  found="$(find_python || true)"
  if [[ -n "$found" ]]; then
    printf '%s\n' "$found"
    return 0
  fi
  if command -v brew >/dev/null 2>&1; then
    if ask_yes_no "DubLocal needs Python 3.11–3.13. Install Python 3.11 with Homebrew now?"; then
      brew install python@3.11 || fail "Homebrew could not install Python 3.11."
      found="$(find_python || true)"
      [[ -n "$found" ]] || fail "Python was installed but DubLocal could not find a compatible interpreter."
      printf '%s\n' "$found"
      return 0
    fi
  fi
  fail "DubLocal needs Python 3.11–3.13. Install a compatible Python, then open DubLocal again."
}

ensure_checkout() {
  if [[ ! -d "$SOURCE_ROOT/.git" ]]; then
    if [[ -e "$SOURCE_ROOT" ]]; then
      fail "The managed DubLocal folder already exists but is not a Git checkout: $SOURCE_ROOT"
    fi
    notify "Preparing the local DubLocal application…"
    git clone --branch "$EXPECTED_BRANCH" --single-branch "$REPO_URL" "$SOURCE_ROOT" \
      || fail "Could not download DubLocal from its official GitHub repository."

    if [[ -n "${BUILD_SHA:-}" ]]; then
      if git -C "$SOURCE_ROOT" cat-file -e "${BUILD_SHA}^{commit}" >/dev/null 2>&1; then
        git -C "$SOURCE_ROOT" reset --hard "$BUILD_SHA" \
          || fail "Could not select the packaged beta revision."
      else
        fail "The packaged beta revision is not available on the official main branch."
      fi
    fi
  fi

  local origin branch
  origin="$(git -C "$SOURCE_ROOT" remote get-url origin 2>/dev/null || true)"
  branch="$(git -C "$SOURCE_ROOT" branch --show-current 2>/dev/null || true)"
  if [[ "$origin" != "$REPO_URL" && "$origin" != "https://github.com/ArrowSK/dublocal" ]]; then
    fail "The managed DubLocal checkout points to an unexpected Git remote. DubLocal will not overwrite it."
  fi
  if [[ "$branch" != "$EXPECTED_BRANCH" ]]; then
    fail "The managed DubLocal checkout is on '$branch', not '$EXPECTED_BRANCH'. DubLocal will not rewrite another branch."
  fi
}

ensure_environment() {
  local current_revision installed_revision base_python
  current_revision="$(git -C "$SOURCE_ROOT" rev-parse HEAD 2>/dev/null || true)"
  installed_revision="$(cat "$SETUP_MARKER" 2>/dev/null || true)"

  if [[ -x "$PYTHON" && -n "$current_revision" && "$installed_revision" == "$current_revision" ]]; then
    return 0
  fi

  # A new checkout or an in-app Git update may introduce dependency changes. Refresh
  # the editable environment before the backend restarts; finished outputs/models are
  # outside this environment and are never touched here.
  SETUP_CHANGED=1
  base_python="$(ensure_python_base)"
  notify "Finishing DubLocal Beta setup…"
  if [[ ! -x "$PYTHON" ]]; then
    "$base_python" -m venv "$VENV" || fail "Could not create DubLocal's private Python environment."
    "$PYTHON" -m pip install --disable-pip-version-check --upgrade pip \
      || fail "Could not prepare pip in DubLocal's private environment."
  fi

  "$PYTHON" -m pip install --disable-pip-version-check -e "$SOURCE_ROOT" \
    || fail "Could not install DubLocal's application dependencies."
  printf '%s\n' "$current_revision" > "$SETUP_MARKER"
}

ffmpeg_has_subtitles() {
  local executable="${1:-}"
  [[ -n "$executable" && -x "$executable" ]] || return 1
  "$executable" -hide_banner -filters 2>/dev/null \
    | /usr/bin/awk '$2 == "subtitles" { found = 1 } END { exit(found ? 0 : 1) }'
}

subtitle_ffmpeg_available() {
  local normal=""
  normal="$(command -v ffmpeg 2>/dev/null || true)"
  if ffmpeg_has_subtitles "$normal"; then
    return 0
  fi
  if ffmpeg_has_subtitles "/opt/homebrew/opt/ffmpeg-full/bin/ffmpeg"; then
    return 0
  fi
  if ffmpeg_has_subtitles "/usr/local/opt/ffmpeg-full/bin/ffmpeg"; then
    return 0
  fi
  return 1
}

check_ffmpeg() {
  if command -v ffmpeg >/dev/null 2>&1 && command -v ffprobe >/dev/null 2>&1; then
    :
  elif command -v brew >/dev/null 2>&1; then
    if ask_yes_no "FFmpeg is required for normal video/audio processing. Install it with Homebrew now? You can choose Not now and still open DubLocal."; then
      brew install ffmpeg || show_message "FFmpeg installation did not complete. DubLocal will still open, but media processing will remain unavailable until FFmpeg is installed."
    fi
  else
    show_message "FFmpeg was not found. DubLocal will open, but normal video/audio processing needs FFmpeg. Install FFmpeg later and reopen the app."
  fi

  # Normal FFmpeg is enough for most DubLocal jobs. Burned-in subtitles additionally
  # require the libass-backed `subtitles` filter, which is not present in every macOS
  # FFmpeg build. A keg-only ffmpeg-full can live beside the normal binary; only the
  # burn-in path selects it. Prompt only after a fresh setup/update so ordinary app
  # launches never nag the user.
  if subtitle_ffmpeg_available || [[ "$SETUP_CHANGED" != "1" ]]; then
    return 0
  fi

  if command -v brew >/dev/null 2>&1; then
    if ask_yes_no "Your FFmpeg can handle normal media, but it does not include subtitle rendering needed for burned Shareable MP4 files. Install the optional Homebrew ffmpeg-full build side-by-side now?"; then
      brew install ffmpeg-full \
        || show_message "The optional ffmpeg-full installation did not complete. DubLocal will still open and standalone/selectable subtitles will keep working; burned-in subtitle export will remain unavailable."
      if subtitle_ffmpeg_available; then
        notify "Subtitle-capable FFmpeg is ready for burned Shareable MP4 exports."
      fi
    fi
  fi
}

ensure_git
ensure_checkout
ensure_environment
check_ffmpeg

LAUNCHER="$SOURCE_ROOT/scripts/macos/launch-dublocal.sh"
[[ -f "$LAUNCHER" ]] || fail "The installed DubLocal launcher is missing."

# A fresh beta setup must take ownership of the single local backend even when an old
# source/development DubLocal instance is already running. Likewise, an in-app packaged
# update/repair can force this bootstrap path so dependency refresh happens before a
# clean restart. Ordinary subsequent app opens simply reuse the healthy managed backend.
if [[ "$SETUP_CHANGED" == "1" || "${DUBLOCAL_FORCE_RESTART:-0}" == "1" ]]; then
  LAUNCH_ACTION="restart"
else
  LAUNCH_ACTION="open"
fi

notify "DubLocal Beta ${BETA_VERSION:-0.6.0b3} is ready."
exec env \
  DUBLOCAL_BETA_BOOTSTRAP="$BOOTSTRAP_PATH" \
  DUBLOCAL_LAUNCH_ACTION="$LAUNCH_ACTION" \
  /bin/zsh "$LAUNCHER"
